apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
    ver: "0.0.1"
    env: staging
    
spec:
  containers:
    - name: mongodb
      image: mongo:4.1.13-bionic
      ports:
        - containerPort: 27017
      args:
        - "mongod"
        - "--auth"
        - "--bind_ip_all"
      env:
        - name: "MONGO_INITDB_ROOT_USERNAME"
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: root_username
        - name: "MONGO_INITDB_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: root_password
        - name: "MONGO_INITDB_DATABASE"
          value: "admin"
      volumeMounts:
        - mountPath: /data/db
          name: nfs-storage
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc1

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
