apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ikontainer
spec:
  selector:
    matchLabels:
      app: mongo-ikontainer
  template:
    metadata:
      labels:
        app: mongo-ikontainer
    spec:
      containers:
        - name: mongo-ikontainer
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-ikontainer-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ikontainer
spec:
  selector:
    app: mongo-ikontainer
  ports:
    - port: 27017
      targetPort: 27017
