kind: PersistentVolume
apiVersion: v1
metadata:
  name: doktor-ikontainer
  labels: 
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mongo-data/ikontainer/{name}
