apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: takahyon/api_mock:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
            
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: flask
