apiVersion: apps/v1
kind: Deployment
metadata:
  name: doktor-upload
  labels:
    app: doktor-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doktor-upload
  template:
    metadata:
      labels:
        app: doktor-upload
    spec:
      containers:
        - name: doktor-upload
          image: takahyon/doktor-upload
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: doktor-upload
spec:
  selector:
    app: doktor-upload
  ports:
    - port: 8080
      targetPort: 3000
  type: LoadBalancer