name: Pull Request Check

on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Validate manifests
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
        with:
          files: "."
          token: ${{ secrets.GITHUB_TOKEN }}
